---
title: "R Notebook"
output: html_notebook
---

# R da karakterlerle calismak

## 1.Karakter Olusturmak

### Bos karakter 

``` {r}

bos_str <- ""
class(bos_str)

ornek <- character(0)
class(ornek)


str(ornek)


ornek[1] <- "Bu birinci degerdir"

is.character(ornek)

as.character(ornek) 
as.character(9)
```

### paste() ve digerleri

```{r}

metin <- "Bu bir karakterdir"
metin

karakter <- "Bu da karakterdir"

c("karakter")


paste(metin)

paste("09838")

paste(metin,karakter)


paste(metin,karakter,sep="/")

paste(metin,karakter,"karakter",metin,sep = ":")


print("YUsuf",quote=FALSE)

noquote("karakter")


toString(1827)

a <- toString(c("asfas",01024,sum(1:100),TRUE))
```

## 2.Temel kavramlar

```{r}
# nchar
nchar("Yusuf Çelik")

#length
length(c("dsa","rhsa","gsa"))

#tolower
tolower("YUSUF")

#toupper
toupper("yusuf")

#chartr
chartr("l","L","Laleliden bir gul aldim")

#abbreviate
renkler <- colors()[1:6]
abbreviate(renkler,minlength = 5)

#substr
substr("Yusuf",2,4)

# grep
v <- c("yusuf","berber","alice","erer","ancak yeter")
grep("er",v)

#sub
v <- c("yusuf","berber","alice","erer","ancak yeter")
sub("er","sdag",v)

```

## 3.Vektorel Islemler

```{r}

sirket_a <- c("R","sql","Python","SPSS","SAS")

sirket_b <- c("sql","R","Python","SPSS","Excel")

sirket_c <- c("R","sql","Python","SAS","SPSS")

# union() -> birbirine ekler
union(sirket_a,sirket_b)
union(sirket_b,sirket_a)

#intersect() -> kesişimini verir
intersect(sirket_a,sirket_b)

# setdiff()-> farklı elemanları verir
setdiff(sirket_a,sirket_b)
setdiff(sirket_b,sirket_a)

# setequal() -> içerdiği elemanlar denk mi değil mi onu kontrol eder
setequal(sirket_a,sirket_c)
setequal(sirket_a,sirket_b)

#identical() -> kümeler aynı mı diye bakar
identical(sirket_a,sirket_c)
identical(sirket_a,sirket_a)
```


## 4. stringr ile islemler

[Stringr Cheat Sheet](https://evoldyn.gitlab.io/evomics-2018/ref-sheets/R_strings.pdf)

### str_detect() esleme saptama islemleri
```{r}
library(stringr)

v <- c("yusuf","berber","alice","erer","ancak yeter")

str_detect(v,"er")

str_which(v,"er")

str_count(v,"er")

str_locate(v,"er")

str_locate_all(v,"er")

```

### str_sub() karakter alt kume
```{r}

str_sub(v,1,3)

birseyler <- c("buyukveri","makineogrenmesiveveri","istatistikveveri","borcamveveri")

str_sub(birseyler, -4,-1)

substring(birseyler,-4,-1)

```

### str_c() birlestirme
```{r}

str_c("ali","ata","bakmayi","birak","millet","uzaya",sep = "_")


```

### str_replace() eslesme degistirme
```{r}
str_sub(v,1,3)

v <- c("yusuf","berber","alice","erer","ancak yeter")

str_replace(v,"er","--")

str_replace_all(v,"er","--")

str_to_lower(v)

str_to_upper(v)

```

### str_length() karakter uzunluk
```{r}
nchar(v)

str_length(v)

a_b <- factor(c(1,1,1,0,0,0),labels = c("birincifaktor","ikincifaktor"))

a_b

# nchar(a_b) Error in nchar(a_b) : 'nchar()' requires a character vector

str_length(a_b)
```